exp_tracker/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('expenses', views.ExpenseListView.as_view(), name='expenses'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
]

expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exp_tracker.urls'))
]

exp_tracker/models.py
from django.db import models
from datetime import datetime
# from django.utils.timezone import now

# Create your models here.

class Account(models.Model):
    name = models.CharField(max_length=100)
    expense = models.FloatField(default=0)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    expense_list = models.ManyToManyField('Expense', blank=True)


class Expense(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)
    date = models.DateField(null=False, default=datetime.now().date())
    long_term = models.BooleanField(default=False)
    interest_rate = models.FloatField(default=0, null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    monthly_expenses = models.FloatField(default=0, null=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        if self.long_term:
            self.monthly_expenses = self.calculate_monthly_expense()
        super(Expense, self).save(*args, **kwargs)


    def calculate_monthly_expense(self):
        if self.long_term:
            if self.interest_rate == 0:
                return self.amount / ((self.end_date - self.date) /30)
            else:
                months = (self.end_date.year - datetime.now().year) * 12 + self.end_date.month - datetime.now().month
                monthly_rate = self.interest_rate / 12 /100
                monthly_expense = (self.amount * monthly_rate) / (1 - (1 + monthly_rate) ** -months)
                return round(monthly_expense, 2)
        else:
            return self.monthly_expense

exp_tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Expense


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove the username similarity validator
        self.fields['password1'].validators = [v for v in self.fields['password1'].validators 
                                            if not v.__class__.__name__ == 'UserAttributeSimilarityValidator']

class ExpenseForm(forms.ModelForm):
    long_term = forms.BooleanField(required=False)


    class Meta:
        model = Expense
        fields = ['name', 'amount', 'interest_rate', 'date', 'end_date', 'long_term']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'interest_rate': forms.NumberInput(attrs={'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'long_term': forms.CheckboxInput(attrs={'class': 'form-control'}),
        }


        def clean(self):
            cleaned_data = super().clean()
            long_term = cleaned_data.get("long_term")
            start_date = cleaned_data.get('date')
            if long_term:
                interest_rate = cleaned_data.get('interest_rate')
                end_date = cleaned_data.get('end_date')
                amount = cleaned_data.get('amount')
                cleaned_data['long_term'] = True     #cleaned_date
            else:
                cleaned_data['end_date'] = None
                cleaned_data['interest_rate'] = None 

            return cleaned_data

exp_tracker/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from exp_tracker import models
from .models import Account, Expense
from .forms import ExpenseForm, CustomUserCreationForm
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.views.generic import ListView
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django.utils.safestring import mark_safe
from django.db.models import Sum, Count, F
import plotly.express as px
from plotly.graph_objs import *


# Create your views here.

def home(request):
    return render(request, 'home/home.html')


from django.contrib.auth.password_validation import MinimumLengthValidator, CommonPasswordValidator, NumericPasswordValidator
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm

class CustomUserCreationForm(BaseUserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove the default help text
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['toast_message'] = {
                'message': 'Registration successful! Please log in with your credentials.',
                'type': 'success'
            }
            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})
    
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['toast_message'] = {
                    'message': f'Welcome back, {username}!',
                    'type': 'success'
                }
                return redirect('expenses')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required
@require_http_methods(['GET', 'POST'])
def logout_view(request):
    logout(request)
    request.session['toast_message'] = {
        'type': 'success',
        'message': 'You have been logged out successfully.'
    }
    return redirect('home')


def generate_graph(data):
    fig = px.bar(data, x='months', y='expenses', title='Monthly Expenses')
    fig.update_layout(
        xaxis=dict(rangeslider=dict(visible=True)),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font_color = 'rgba(0,0,0,1)'
    )
    fig.update_traces(marker_color='#008c41')

    graph_json = fig.to_json()
    return graph_json


class ExpenseListView(FormView):
    template_name = 'exp_tracker/expenses_list.html'
    form_class = ExpenseForm
    success_url = '/'

    def form_valid(self, form):
        account, _ = Account.objects.get_or_create(user=self.request.user)

        expense = Expense(
            name = form.cleaned_data['name'],
            amount = form.cleaned_data['amount'],
            interest_rate = form.cleaned_data['interest_rate'],
            date = form.cleaned_data['date'],
            end_date = form.cleaned_data['end_date'],
            long_term = form.cleaned_data['long_term'],
            user = self.request.user
        )
        expense.save()
        account.expense_list.add(expense)
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        accounts = Account.objects.filter(user=user)

        expense_data_graph = {}
        expense_data = {}

        for account in accounts:
            expenses = account.expense_list.all()
            for expense in expenses:
                if expense.long_term and expense.monthly_expenses:
                    current_date = expense.date
                    while current_date <= expense.end_date:
                        year_month = current_date.strftime('%Y-%m')
                        if year_month not in expense_data_graph:
                            expense_data_graph[year_month] = []

                        expense_data_graph[year_month].append({
                            'name': expense.name,
                            'amount': expense.monthly_expenses,
                            'date': expense.date,
                            'end_date': expense.end_date,
                        })

                        current_date = current_date + relativedelta(months=1)
                else:
                    year_month = expense.date.strftime('%Y-%m')
                    if year_month not in expense_data_graph:
                        expense_data_graph[year_month] = []

                        expense_data_graph[year_month].append({
                            'name': expense.name,
                            'amount': expense.amount,
                            'date': expense.date,
                        })

        for account in accounts:
            expenses = account.expense_list.all()
            for expense in expenses:
                if expense.long_term and expense.monthly_expenses:
                    current_date = expense.date
                    year_month = current_date.strftime('%Y-%m')
                    if year_month not in expense_data:
                        expense_data[year_month] = []

                    expense_data[year_month].append({
                        'name': expense.name,
                        'amount': expense.amount,
                        'date': current.date,
                        'end_date': expense.end_date,
                        'long_term': expense.long_term,
                    })

                        # Move to the next month
                    current_date = current_date + relativedelta(months=1)
                else:
                    year_month = expense.date.strftime('%Y-%m')
                    if year_month not in expense_data:
                        expense_data[year_month] = []

                    expense_data[year_month].append({
                        'name': expense.name,
                        'amount': expense.amount,
                        'date': expense.date,
                    })

        aggregated_data = [{ 'year_month': key, 'expenses': sum(item['amount'] for item in value)} for key, value in expense_data_graph.items()]

        context['expense_data'] = expense_data
        context['aggregated_data'] = aggregated_data

        graph_data = {
            'months': [item['year_month'] for item in aggregated_data],
            'expenses': [item['expenses'] for item in aggregated_data],
        }

        graph_data['chart'] = generate_graph(graph_data)
        context['graph_data'] = mark_safe(graph_data['chart'])

        return context

        

exp_tracker/templates/exp_tracker/expenses_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Expenses - Expense Tracker{% endblock %}

{% block content %}
<!-- Navigation Bar -->
<nav class="main-nav">
    <div class="nav-container">
        <div class="nav-brand">
            <i class="fas fa-wallet"></i>
            <span>Expense Tracker</span>
        </div>
        <div class="nav-actions">
            <a href="{% url 'logout' %}" class="nav-link">
                <i class="fas fa-sign-out-alt"></i>
                <span>Logout</span>
            </a>
        </div>
    </div>
</nav>

<!-- Main Content -->
<main class="main-content">
    <div class="page-container">
        <!-- Page Header -->
        <header class="page-header">
            <h1>My Expenses</h1>
        </header>

        <!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <script>
            $(document).ready(function () {
                var longTermCheckBox = $('#id_long_term');
                var longTermFields = $('#interest_rate, #end_date');

                longTermFields.hide();

                longTermCheckBox.on('change', function () {
                    if (longTermCheckBox.is(':checked')) {
                        longTermFields.show();
                    } else {
                        longTermFields.hide();
                    }
                });
            });
        </script>

        <!-- Dashboard Grid -->
        <div class="dashboard-grid">
            <!-- Graph Section -->
            <section class="dashboard-card graph-section">
                <h2 class="section-title">
                    <i class="fas fa-chart-bar"></i>
                    Monthly Expenses Overview
                </h2>
                <div class="plotly-chart" id="plotly-chart"></div>
            </section>

            <!-- Expenses List Section -->
            <section class="dashboard-card expenses-section">
                <h2 class="section-title">
                    <i class="fas fa-list"></i>
                    Expenses List
                </h2>

                <div class="expenses-list">
                    {% for year_month, expenses in expense_data.items %}
                    <div class="month-group">
                        <h3 class="month-title">
                            <i class="fas fa-calendar-alt"></i>
                            {{ year_month }}
                        </h3>
                        {% for expense in expenses %}
                        <div class="expense-item">
                            <div class="expense-details">
                                <h4 class="expense-name">{{ expense.name }}</h4>
                                <div class="expense-date">
                                    {% if expense.long_term %}
                                    <i class="fas fa-calendar-week"></i>
                                    <span>From: {{ expense.date }}</span><br>
                                    <i class="fas fa-calendar-check"></i>
                                    <span>To: {{ expense.end_date }}</span>
                                    {% else %}
                                    <i class="fas fa-calendar-day"></i>
                                    <span>{{ expense.date }}</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="expense-amount">
                                <span class="amount">₹{{ expense.amount }}</span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </section>

            <!-- Add Expense Section -->
            <section class="dashboard-card add-expense-section">
                <h2 class="section-title">
                    <i class="fas fa-plus-circle"></i>
                    Add New Expense
                </h2>
                <form method="post" class="expense-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="checkbox-group">
                            {{ form.long_term.label_tag }}
                            {{ form.long_term }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <i class="fas fa-tag input-icon"></i>
                            {{ form.name }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <i class="fas fa-rupee-sign input-icon"></i>
                            {{ form.amount }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <i class="fas fa-calendar input-icon"></i>
                            {{ form.date }}
                        </div>
                    </div>

                    <div id="end_date" class="form-group">
                        <div class="input-group">
                            <i class="fas fa-calendar-check input-icon"></i>
                            {{ form.end_date }}
                        </div>
                    </div>

                    <div id="interest_rate" class="form-group">
                        <div class="input-group">
                            <i class="fas fa-percentage input-icon"></i>
                            {{ form.interest_rate }}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">
                        <i class="fas fa-plus"></i> Add Expense
                    </button>
                </form>
            </section>
        </div>

        <!-- Plotly Chart -->
        <script>
            var graphData = {{ graph_data | safe }};
            var layout = {
                ...graphData.layout,
                paper_bgcolor: 'rgba(0,0,0,0)',
                plot_bgcolor: 'rgba(0,0,0,0)',
                font: {
                    family: 'var(--font-family)',
                    color: 'var(--text-color)'
                },
                margin: { t: 20, r: 20, b: 40, l: 60 },
                height: 400,
                autosize: true
            };
            Plotly.newPlot('plotly-chart', graphData.data, layout);
            window.addEventListener('resize', function () {
                Plotly.Plots.resize('plotly-chart');
            });
        </script>
    </div>
</main>
{% endblock %}